### ISSUE TITLE
Running on macos

### ISSUE THREAD

**Issue by ArgoHA** [FelixHertlein/inv3d-model#1]
Hey, thanks for your repo. Is it possible to run it on macos (cpu)?
Current docker implementation seems to require nvidia gpu with drivers. I ran commands from your readme in VSCode and here is what I got:

```
 => [dev_container_auto_added_stage_label  3/10] RUN apt update && apt -  32.7s
 => [dev_container_auto_added_stage_label  4/10] RUN apt install -y pyth  62.5s
 => ERROR [dev_container_auto_added_stage_label  5/10] RUN pip3 install t  1.4s
------
 > [dev_container_auto_added_stage_label  5/10] RUN pip3 install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1+cu118 --index-url https://download.pytorch.org/whl/cu118:
#0 0.384 Looking in indexes: https://download.pytorch.org/whl/cu118
#0 1.331 ERROR: Could not find a version that satisfies the requirement torch==2.0.0+cu118 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
#0 1.331 ERROR: No matching distribution found for torch==2.0.0+cu118
------
Dockerfile-with-features:9
--------------------
   7 |     RUN apt install -y python3-pip git ffmpeg libsm6 libxext6 
   8 |     
   9 | >>> RUN pip3 install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1+cu118 --index-url https://download.pytorch.org/whl/cu118
  10 |     
  11 |     COPY requirements.txt /opt/app/requirements.txt
--------------------
ERROR: failed to solve: process "/bin/sh -c pip3 install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1+cu118 --index-url https://download.pytorch.org/whl/cu118" did not complete successfully: exit code: 1
[918138 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/wp/8ssxlpmj6kx4w038rb7fn6vw0000gn/T/devcontainercli/container-features/0.51.1-1694666510631/Dockerfile-with-features -t vsc-inv3d-model-82fcf21fa1cce635cf87854bc6313e476165cd08b53073e8e836ad076755b3af --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/argosaakyan/Data/Veryfi/inv3d-model
[918138 ms]     at CAA (/Users/argosaakyan/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:463:1752)
[918138 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[918138 ms]     at async jw (/Users/argosaakyan/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:462:1691)
[918139 ms]     at async FK (/Users/argosaakyan/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:462:610)
[918139 ms]     at async FAA (/Users/argosaakyan/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:479:3660)
[918139 ms]     at async GC (/Users/argosaakyan/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[918139 ms]     at async VeA (/Users/argosaakyan/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:611:12240)
[918139 ms]     at async WeA (/Users/argosaakyan/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:611:11981)
[918152 ms] Exit code 1
[918155 ms] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/argosaakyan/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/argosaakyan/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-427a6f51-e56e-4159-9046-2835dc487b831694666506936 --workspace-folder /Users/argosaakyan/Data/Veryfi/inv3d-model --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/argosaakyan/Data/Veryfi/inv3d-model --id-label devcontainer.config_file=/Users/argosaakyan/Data/Veryfi/inv3d-model/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/argosaakyan/Data/Veryfi/inv3d-model/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[918155 ms] Exit code 1
```

Please, let me know how to run your repo in alternative way.

**Comment by FelixHertlein** [comment]
Out of the box it is not possible but you can remove the gpu dependency with a few code adaptions.

.devcontainer/devcontainer.json 
-> remove the runArgs

Dockerfile 
-> Select another base image with ubuntu and and the same python already preinstalled 
-> Remove '+cu118' from package versions

inference.py 
-> remove L39,  L59 and L74

I hope I thought of all places to adapt. 
Let me know if it worked!

**Comment by ArgoHA** [comment]
I ended up changing:
Dockerfile - ubuntu:22.04, torch installation, pkg-config libhdf5-dev
requirements.txt - h5py and numpy versions
devcontainer.json - commented runArgs
model_zoo, geotr_core, position_encoding - removed .cuda
inference.py - changed device type to cpu

After that I was able to build container and run inference, thanks!
Let me know if you need me to share the code.

**Comment by FelixHertlein** [comment]
Nice! I personally don't need the adapted code, but maybe someone else reading this issue?

You could upload the code here and then we can close the issue.
